### PR TITLE
Fix HPKP pins verification

### LINKED ISSUE #8: Twitter.com HPKP pin check failed

### PR DESCRIPTION
**Pull request by sfionov**
Fixes #8.

The problem was that HPKP pins check performed on chain provided by server, not on complete chain.

### CODE REVIEW

**Review by ameshkov — APPROVED** [review]

File: src/AGCertificateVerifier.cpp [hunk 1]
```diff
@@ -196,10 +192,13 @@ AGVerifyResult AGCertificateVerifier::verifyDNSName(const std::string &dnsName,
...
  * @param store CA store
+ * @param dnsName Host name
  * @param certChain Certificate chain
+ * @param basicCheckOnly Don't perforn sha1 deprecation and HPKP checks
  * @return Verify result
  */
-AGVerifyResult AGCertificateVerifier::verifyChain(X509_STORE *store, STACK_OF(X509) *certChain) {
+AGVerifyResult AGCertificateVerifier::verifyChain(X509_STORE *store, STACK_OF(X509) *certChain,
+                                                  const std::string &dnsName, bool basicCheckOnly) {
     // Initialize cert store context
```
Comment (hmage) [inline src/AGCertificateVerifier.cpp:202]: Minor nitpick -- doxygen doc parameter order is different from actual parameter order.

**Review by hmage — APPROVED** [review]

**Review by sxgunchenko — APPROVED** [review]
